# v10: image quality gate over v9.
# Goal: do not publish autogenerated source title-cards as news images.
# Use a real article/photo image when available; otherwise publish a clean text post
# with link preview disabled instead of an ugly heading-card picture.

import re
import json
import html
import time
import urllib.parse
from datetime import datetime

import requests

import news_bot_v9 as v9

b = v9.b

# v10 deliberately allows text-only fallback. This prevents ugly autogenerated
# social preview cards from Interfax and other sources.
b.IMAGE_REQUIRED = False

BAD_IMAGE_TOKENS = [
    "logo", "logos", "sprite", "icon", "favicon", "avatar", "placeholder",
    "blank", "transparent", "counter", "pixel", "button", "banner", "advert",
    "ads", "share", "social", "og-image", "og_image", "ogimage", "preview-card",
    "card", "facebook", "twitter", "telegram", "vk.com", "yandex",
]


def host_of(url):
    return urllib.parse.urlparse(url or "").netloc.lower()


def is_interfax_article(url):
    return "interfax.ru" in host_of(url)


def rewrite_image_url(url):
    if not url:
        return url
    # BBC RSS often gives tiny 240px thumbnails. Telegram needs bigger photos.
    url = url.replace("/standard/240/", "/standard/976/")
    url = url.replace("/ace/standard/240/", "/ace/standard/976/")
    url = url.replace("/standard/320/", "/standard/976/")
    return url


def bad_image_url(url, article_url=""):
    if not url:
        return True
    u = url.lower()
    h = host_of(url)
    # Interfax frequently exposes a generated social card with the title as og:image.
    # Until a reliable real-photo parser is proven for Interfax, do not use Interfax-hosted images.
    if "interfax.ru" in h or is_interfax_article(article_url):
        return True
    if not url.startswith(("http://", "https://")):
        return True
    if any(token in u for token in BAD_IMAGE_TOKENS):
        return True
    if u.endswith((".svg", ".gif", ".ico")):
        return True
    return False


def srcset_best(srcset):
    if not srcset:
        return None
    best_url = None
    best_score = -1
    for part in srcset.split(","):
        chunk = part.strip().split()
        if not chunk:
            continue
        url = chunk[0]
        score = 0
        if len(chunk) > 1:
            m = re.search(r"(\d+)(?:w|x)?", chunk[1])
            if m:
                score = int(m.group(1))
        if score >= best_score:
            best_url = url
            best_score = score
    return best_url


def image_candidates_from_html(page, base_url):
    candidates = []

    # Prefer images from article/figure blocks over generic og:image.
    blocks = []
    blocks += re.findall(r"<figure[^>]*>.*?</figure>", page, flags=re.I | re.S)
    blocks += re.findall(r"<article[^>]*>.*?</article>", page, flags=re.I | re.S)
    blocks.append(page[:500000])

    for block in blocks:
        for tag in re.findall(r"<img[^>]+>", block, flags=re.I):
            attrs = {}
            for key, value in re.findall(r"([a-zA-Z0-9_:-]+)=[\"']([^\"']+)[\"']", tag):
                attrs[key.lower()] = value
            raw = (
                srcset_best(attrs.get("srcset", ""))
                or attrs.get("data-src")
                or attrs.get("data-original")
                or attrs.get("data-lazy-src")
                or attrs.get("data-url")
                or attrs.get("src")
            )
            url = rewrite_image_url(b.abs_url(raw, base_url)) if raw else None
            if url and not bad_image_url(url, base_url) and url not in candidates:
                candidates.append(url)
        if candidates:
            break
    return candidates


def page_info_v10(url):
    if not url or b.is_google(url):
        return {}
    try:
        r = requests.get(
            url,
            headers={"User-Agent": "Mozilla/5.0 SkySakhNewsBot/1.0"},
            timeout=30,
            allow_redirects=True,
        )
        if r.status_code >= 400:
            return {}
        page = r.text[:900000]
        final_url = r.url or url
        title_match = re.search(r"<title[^>]*>(.*?)</title>", page, re.I | re.S)
        title = b.clean(b.meta(page, "og:title") or b.meta(page, "twitter:title") or (title_match.group(1) if title_match else ""))
        desc = b.clean(b.meta(page, "og:description") or b.meta(page, "description") or b.meta(page, "twitter:description"))

        images = image_candidates_from_html(page, final_url)
        og = rewrite_image_url(b.abs_url(b.meta(page, "og:image") or b.meta(page, "twitter:image"), final_url))
        if og and not bad_image_url(og, final_url) and og not in images:
            images.append(og)

        paragraphs = []
        for raw in re.findall(r"<p[^>]*>(.*?)</p>", page, re.I | re.S):
            text = b.clean(raw)
            if len(text) > 55 and not any(x in text.lower() for x in ("cookie", "javascript", "подпис", "реклама", "newsletter", "advertisement")):
                paragraphs.append(text)
            if len(paragraphs) >= 4:
                break
        page_text = " ".join(paragraphs)[:1600]
        if title and page_text and b.title_overlap(title, page_text) < 0.10:
            page_text = ""

        return {
            "url": final_url,
            "title": title,
            "desc": desc,
            "image": images[0] if images else None,
            "image_candidates": images,
            "published": b.iso_dt(b.meta(page, "article:published_time") or b.meta(page, "datePublished")),
            "text": page_text,
        }
    except Exception as exc:
        b.log("page read failed: " + str(exc))
        return {}


def rss_image_v10(entry, raw, link):
    # Do not use Interfax RSS/meta images; they are often generated title cards.
    if is_interfax_article(link):
        return None
    for key in ("media_thumbnail", "media_content"):
        for item in entry.get(key, []) or []:
            if isinstance(item, dict) and item.get("url"):
                url = rewrite_image_url(b.abs_url(str(item["url"]), link))
                if url and not bad_image_url(url, link):
                    return url
    found = re.search(r'<img[^>]+src=["\']([^"\']+)["\']', raw or "", re.I)
    if found:
        url = rewrite_image_url(b.abs_url(found.group(1), link))
        if url and not bad_image_url(url, link):
            return url
    return None


def fetch_image_bytes_v10(url):
    if bad_image_url(url):
        b.log("image rejected as social/logo/card: " + str(url)[:90])
        return None
    try:
        r = requests.get(
            url,
            headers={"User-Agent": "Mozilla/5.0", "Accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8"},
            timeout=35,
            allow_redirects=True,
        )
        if r.status_code >= 400:
            b.log(f"image bad status {r.status_code}: {url[:90]}")
            return None
        content_type = (r.headers.get("content-type") or "").split(";")[0].lower()
        data = r.content
        if content_type == "image/svg+xml" or not content_type.startswith("image/"):
            b.log(f"image bad content-type {content_type}: {url[:90]}")
            return None
        # Raised threshold: tiny thumbnails and site UI assets are rejected.
        if len(data) < 15_000 or len(data) > 9_500_000:
            b.log(f"image bad size {len(data)}: {url[:90]}")
            return None
        ext = {"image/jpeg": "jpg", "image/jpg": "jpg", "image/png": "png", "image/webp": "webp"}.get(content_type, "jpg")
        return data, content_type, f"news.{ext}"
    except Exception as exc:
        b.log("image download failed: " + str(exc))
        return None


def tg_text(item, text):
    token = b.os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
    chat = b.os.getenv("TELEGRAM_CHANNEL_ID", "").strip()
    if not token or not chat:
        raise RuntimeError("Telegram secrets missing")
    payload = {
        "chat_id": chat,
        "text": text,
        "parse_mode": "HTML",
        "link_preview_options": json.dumps({"is_disabled": True}, ensure_ascii=False),
    }
    r = requests.post(f"https://api.telegram.org/bot{token}/sendMessage", data=payload, timeout=90)
    if r.status_code >= 400:
        raise RuntimeError(r.text[:700])
    return r.json()


def main_v10():
    state = b.load_state()
    b.log("Сбор кандидатов")
    items = b.collect(state)
    b.log(f"Кандидатов после фильтра v10: {len(items)}")
    if not items:
        b.save_state(state)
        return

    ordered = b.select_order(items)
    published = 0
    for item in ordered:
        if published >= b.POSTS_PER_RUN:
            break
        if item["url"] in state.get("published_urls", []):
            continue
        try:
            row = b.generate_row(item)
            has_image = bool(item.get("image_file"))
            if has_image:
                caption = b.make_post(row, item, 980)
                b.log(f"publish real-photo: {item['category_hint']} | {item['source']} | {item['title'][:90]}")
                result = b.tg_photo(item, caption)
                method = "sendPhoto/upload-real-image"
            else:
                text = b.make_post(row, item, 2600)
                b.log(f"publish text-no-preview: {item['category_hint']} | {item['source']} | {item['title'][:90]}")
                result = tg_text(item, text)
                method = "sendMessage/no-preview-no-bad-card"
        except Exception as exc:
            b.log("candidate skipped: " + str(exc))
            continue
        if result.get("ok"):
            state.setdefault("published_urls", []).append(item["url"])
            state.setdefault("published_title_hashes", []).append(item["title_hash"])
            state.setdefault("last_posts", []).append({
                "time_sakhalin": datetime.now(b.TZ).isoformat(timespec="seconds"),
                "source": item["source"],
                "category": row.get("category") or item["category_hint"],
                "title": row.get("title_ru") or item["title"],
                "url": item["url"],
                "published_at": item.get("published_at"),
                "with_image": bool(item.get("image_file")),
                "publish_method": method,
                "score": item.get("score"),
            })
            published += 1
            time.sleep(12)
    b.log(f"Опубликовано: {published}")
    b.save_state(state)


b.page_info = page_info_v10
b.rss_image = rss_image_v10
b.fetch_image_bytes = fetch_image_bytes_v10
b.main = main_v10

if __name__ == "__main__":
    b.main()
